package com.accenture.quizhub.dto;

import com.accenture.quizhub.dto.request.*;
import com.accenture.quizhub.dto.response.CommentResponse;
import com.accenture.quizhub.dto.response.McqResponse;
import com.accenture.quizhub.enums.Difficulty;
import com.accenture.quizhub.enums.McqStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pure unit tests for request DTOs (all annotated with {@code @Data}).
 * Covers getters, setters, equals, hashCode and toString generated by Lombok.
 * No Spring context required.
 */
@DisplayName("DtoGroup2 – Request DTOs")
class DtoGroup2Test {

    // =========================================================================
    // AddUserRequest
    // =========================================================================

    @Nested
    @DisplayName("AddUserRequest")
    class AddUserRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for all fields")
        void settersAndGetters_roundTrip() {
            AddUserRequest req = new AddUserRequest();
            req.setEnterpriseId("EMP001");
            req.setFullName("Alice Smith");
            req.setEmail("alice@example.com");
            req.setRole("SME");
            req.setTechStackIds(List.of(1L, 2L, 3L));

            assertThat(req.getEnterpriseId()).isEqualTo("EMP001");
            assertThat(req.getFullName()).isEqualTo("Alice Smith");
            assertThat(req.getEmail()).isEqualTo("alice@example.com");
            assertThat(req.getRole()).isEqualTo("SME");
            assertThat(req.getTechStackIds()).containsExactly(1L, 2L, 3L);
        }

        @Test
        @DisplayName("no-args constructor produces all-null fields")
        void noArgsConstructor_allNull() {
            AddUserRequest req = new AddUserRequest();
            assertThat(req.getEnterpriseId()).isNull();
            assertThat(req.getFullName()).isNull();
            assertThat(req.getEmail()).isNull();
            assertThat(req.getRole()).isNull();
            assertThat(req.getTechStackIds()).isNull();
        }

        @Test
        @DisplayName("techStackIds can be null (optional field)")
        void techStackIds_canBeNull() {
            AddUserRequest req = new AddUserRequest();
            req.setEnterpriseId("EMP002");
            req.setRole("ADMIN");
            assertThat(req.getTechStackIds()).isNull();
        }

        @Test
        @DisplayName("techStackIds accepts empty list")
        void techStackIds_emptyList() {
            AddUserRequest req = new AddUserRequest();
            req.setTechStackIds(List.of());
            assertThat(req.getTechStackIds()).isEmpty();
        }

        @Test
        @DisplayName("ADMIN role can be set")
        void role_admin() {
            AddUserRequest req = new AddUserRequest();
            req.setRole("ADMIN");
            assertThat(req.getRole()).isEqualTo("ADMIN");
        }

        @Test
        @DisplayName("equals: two instances with same values are equal")
        void equals_sameValues() {
            AddUserRequest a = new AddUserRequest();
            a.setEnterpriseId("EMP003");
            a.setFullName("Bob");
            a.setEmail("bob@test.com");
            a.setRole("SME");
            a.setTechStackIds(List.of(10L));

            AddUserRequest b = new AddUserRequest();
            b.setEnterpriseId("EMP003");
            b.setFullName("Bob");
            b.setEmail("bob@test.com");
            b.setRole("SME");
            b.setTechStackIds(List.of(10L));

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different enterpriseId produces unequal objects")
        void equals_differentEnterpriseId_notEqual() {
            AddUserRequest a = new AddUserRequest();
            a.setEnterpriseId("EMP100");
            a.setRole("SME");

            AddUserRequest b = new AddUserRequest();
            b.setEnterpriseId("EMP200");
            b.setRole("SME");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains enterpriseId and role")
        void toString_containsKeyFields() {
            AddUserRequest req = new AddUserRequest();
            req.setEnterpriseId("EMP999");
            req.setRole("ADMIN");
            assertThat(req.toString()).contains("EMP999").contains("ADMIN");
        }

        @Test
        @DisplayName("updating a field via setter is reflected in getter")
        void setter_updatesField() {
            AddUserRequest req = new AddUserRequest();
            req.setFullName("Original Name");
            req.setFullName("Updated Name");
            assertThat(req.getFullName()).isEqualTo("Updated Name");
        }
    }

    // =========================================================================
    // RegisterRequest
    // =========================================================================

    @Nested
    @DisplayName("RegisterRequest")
    class RegisterRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for all fields")
        void settersAndGetters_roundTrip() {
            RegisterRequest req = new RegisterRequest();
            req.setEnterpriseId("EMP010");
            req.setFullName("Carol White");
            req.setEmail("carol@example.com");
            req.setPassword("SecurePass1");
            req.setTechStackIds(List.of(5L, 6L));

            assertThat(req.getEnterpriseId()).isEqualTo("EMP010");
            assertThat(req.getFullName()).isEqualTo("Carol White");
            assertThat(req.getEmail()).isEqualTo("carol@example.com");
            assertThat(req.getPassword()).isEqualTo("SecurePass1");
            assertThat(req.getTechStackIds()).containsExactly(5L, 6L);
        }

        @Test
        @DisplayName("no-args constructor produces all-null fields")
        void noArgsConstructor_allNull() {
            RegisterRequest req = new RegisterRequest();
            assertThat(req.getEnterpriseId()).isNull();
            assertThat(req.getFullName()).isNull();
            assertThat(req.getEmail()).isNull();
            assertThat(req.getPassword()).isNull();
            assertThat(req.getTechStackIds()).isNull();
        }

        @Test
        @DisplayName("techStackIds is optional and can be null")
        void techStackIds_optional() {
            RegisterRequest req = new RegisterRequest();
            req.setEnterpriseId("EMP011");
            req.setPassword("Password1");
            assertThat(req.getTechStackIds()).isNull();
        }

        @Test
        @DisplayName("techStackIds accepts multiple stack IDs")
        void techStackIds_multiple() {
            RegisterRequest req = new RegisterRequest();
            req.setTechStackIds(List.of(1L, 2L, 3L, 4L));
            assertThat(req.getTechStackIds()).hasSize(4).containsExactly(1L, 2L, 3L, 4L);
        }

        @Test
        @DisplayName("equals: two instances with same values are equal")
        void equals_sameValues() {
            RegisterRequest a = new RegisterRequest();
            a.setEnterpriseId("EMP012");
            a.setFullName("Dave");
            a.setEmail("dave@test.com");
            a.setPassword("Password1");

            RegisterRequest b = new RegisterRequest();
            b.setEnterpriseId("EMP012");
            b.setFullName("Dave");
            b.setEmail("dave@test.com");
            b.setPassword("Password1");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different email produces unequal objects")
        void equals_differentEmail_notEqual() {
            RegisterRequest a = new RegisterRequest();
            a.setEnterpriseId("EMP013");
            a.setEmail("a@test.com");

            RegisterRequest b = new RegisterRequest();
            b.setEnterpriseId("EMP013");
            b.setEmail("b@test.com");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains enterpriseId and email")
        void toString_containsKeyFields() {
            RegisterRequest req = new RegisterRequest();
            req.setEnterpriseId("EMP014");
            req.setEmail("emp014@test.com");
            assertThat(req.toString()).contains("EMP014").contains("emp014@test.com");
        }

        @Test
        @DisplayName("password field is mutable via setter")
        void password_mutableViaSetter() {
            RegisterRequest req = new RegisterRequest();
            req.setPassword("OldPass1");
            req.setPassword("NewPass2");
            assertThat(req.getPassword()).isEqualTo("NewPass2");
        }
    }

    // =========================================================================
    // McqRequest
    // =========================================================================

    @Nested
    @DisplayName("McqRequest")
    class McqRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for all fields")
        void settersAndGetters_roundTrip() {
            McqRequest req = new McqRequest();
            req.setQuestionStem("What is Spring Boot?");
            req.setTechStackId(10L);
            req.setTopicId(20L);
            req.setDifficulty(Difficulty.MEDIUM);
            req.setOptionA("A framework");
            req.setOptionB("A language");
            req.setOptionC("A database");
            req.setOptionD("An OS");
            req.setCorrectAnswer("A");
            req.setSendForReview(true);

            assertThat(req.getQuestionStem()).isEqualTo("What is Spring Boot?");
            assertThat(req.getTechStackId()).isEqualTo(10L);
            assertThat(req.getTopicId()).isEqualTo(20L);
            assertThat(req.getDifficulty()).isEqualTo(Difficulty.MEDIUM);
            assertThat(req.getOptionA()).isEqualTo("A framework");
            assertThat(req.getOptionB()).isEqualTo("A language");
            assertThat(req.getOptionC()).isEqualTo("A database");
            assertThat(req.getOptionD()).isEqualTo("An OS");
            assertThat(req.getCorrectAnswer()).isEqualTo("A");
            assertThat(req.isSendForReview()).isTrue();
        }

        @Test
        @DisplayName("no-args constructor: sendForReview defaults to false")
        void noArgsConstructor_sendForReview_defaultFalse() {
            McqRequest req = new McqRequest();
            assertThat(req.isSendForReview()).isFalse();
        }

        @Test
        @DisplayName("no-args constructor: nullable fields are null")
        void noArgsConstructor_nullableFieldsNull() {
            McqRequest req = new McqRequest();
            assertThat(req.getQuestionStem()).isNull();
            assertThat(req.getTechStackId()).isNull();
            assertThat(req.getTopicId()).isNull();
            assertThat(req.getDifficulty()).isNull();
        }

        @Test
        @DisplayName("topicId is optional and can be null")
        void topicId_optional() {
            McqRequest req = new McqRequest();
            req.setTechStackId(5L);
            assertThat(req.getTopicId()).isNull();
        }

        @Test
        @DisplayName("equals: two instances with same values are equal")
        void equals_sameValues() {
            McqRequest a = new McqRequest();
            a.setQuestionStem("Q1");
            a.setTechStackId(1L);
            a.setDifficulty(Difficulty.EASY);
            a.setCorrectAnswer("B");

            McqRequest b = new McqRequest();
            b.setQuestionStem("Q1");
            b.setTechStackId(1L);
            b.setDifficulty(Difficulty.EASY);
            b.setCorrectAnswer("B");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different correctAnswer produces unequal objects")
        void equals_differentCorrectAnswer_notEqual() {
            McqRequest a = new McqRequest();
            a.setQuestionStem("Q");
            a.setCorrectAnswer("A");

            McqRequest b = new McqRequest();
            b.setQuestionStem("Q");
            b.setCorrectAnswer("B");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("all Difficulty enum values can be set")
        void allDifficultyValues() {
            for (Difficulty d : Difficulty.values()) {
                McqRequest req = new McqRequest();
                req.setDifficulty(d);
                assertThat(req.getDifficulty()).isEqualTo(d);
            }
        }

        @Test
        @DisplayName("toString contains questionStem")
        void toString_containsQuestionStem() {
            McqRequest req = new McqRequest();
            req.setQuestionStem("What is JPA?");
            assertThat(req.toString()).contains("What is JPA?");
        }

        @Test
        @DisplayName("sendForReview can be toggled")
        void sendForReview_toggled() {
            McqRequest req = new McqRequest();
            assertThat(req.isSendForReview()).isFalse();
            req.setSendForReview(true);
            assertThat(req.isSendForReview()).isTrue();
            req.setSendForReview(false);
            assertThat(req.isSendForReview()).isFalse();
        }
    }

    // =========================================================================
    // AssignReviewerRequest
    // =========================================================================

    @Nested
    @DisplayName("AssignReviewerRequest")
    class AssignReviewerRequestTests {

        @Test
        @DisplayName("setters and getter round-trip for reviewerId")
        void setterAndGetter_reviewerId() {
            AssignReviewerRequest req = new AssignReviewerRequest();
            req.setReviewerId(42L);
            assertThat(req.getReviewerId()).isEqualTo(42L);
        }

        @Test
        @DisplayName("no-args constructor: reviewerId is null")
        void noArgsConstructor_reviewerIdNull() {
            AssignReviewerRequest req = new AssignReviewerRequest();
            assertThat(req.getReviewerId()).isNull();
        }

        @Test
        @DisplayName("equals: same reviewerId produces equal objects")
        void equals_sameReviewerId() {
            AssignReviewerRequest a = new AssignReviewerRequest();
            a.setReviewerId(99L);
            AssignReviewerRequest b = new AssignReviewerRequest();
            b.setReviewerId(99L);

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different reviewerIds produce unequal objects")
        void equals_differentReviewerId_notEqual() {
            AssignReviewerRequest a = new AssignReviewerRequest();
            a.setReviewerId(1L);
            AssignReviewerRequest b = new AssignReviewerRequest();
            b.setReviewerId(2L);

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains reviewerId")
        void toString_containsReviewerId() {
            AssignReviewerRequest req = new AssignReviewerRequest();
            req.setReviewerId(55L);
            assertThat(req.toString()).contains("55");
        }

        @Test
        @DisplayName("reviewerId can be updated via setter")
        void setter_updatesReviewerId() {
            AssignReviewerRequest req = new AssignReviewerRequest();
            req.setReviewerId(10L);
            req.setReviewerId(20L);
            assertThat(req.getReviewerId()).isEqualTo(20L);
        }
    }

    // =========================================================================
    // ChangePasswordRequest
    // =========================================================================

    @Nested
    @DisplayName("ChangePasswordRequest")
    class ChangePasswordRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for both fields")
        void settersAndGetters_roundTrip() {
            ChangePasswordRequest req = new ChangePasswordRequest();
            req.setCurrentPassword("OldPass1");
            req.setNewPassword("NewPass2");

            assertThat(req.getCurrentPassword()).isEqualTo("OldPass1");
            assertThat(req.getNewPassword()).isEqualTo("NewPass2");
        }

        @Test
        @DisplayName("no-args constructor: both fields null")
        void noArgsConstructor_allNull() {
            ChangePasswordRequest req = new ChangePasswordRequest();
            assertThat(req.getCurrentPassword()).isNull();
            assertThat(req.getNewPassword()).isNull();
        }

        @Test
        @DisplayName("equals: same passwords produce equal objects")
        void equals_sameValues() {
            ChangePasswordRequest a = new ChangePasswordRequest();
            a.setCurrentPassword("Abc12345");
            a.setNewPassword("Xyz67890");

            ChangePasswordRequest b = new ChangePasswordRequest();
            b.setCurrentPassword("Abc12345");
            b.setNewPassword("Xyz67890");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different newPassword produces unequal objects")
        void equals_differentNewPassword_notEqual() {
            ChangePasswordRequest a = new ChangePasswordRequest();
            a.setCurrentPassword("Same1234");
            a.setNewPassword("NewPass1");

            ChangePasswordRequest b = new ChangePasswordRequest();
            b.setCurrentPassword("Same1234");
            b.setNewPassword("NewPass2");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains field representation")
        void toString_notNull() {
            ChangePasswordRequest req = new ChangePasswordRequest();
            req.setCurrentPassword("CurrPass1");
            req.setNewPassword("NewPass99");
            assertThat(req.toString()).isNotNull().contains("ChangePasswordRequest");
        }

        @Test
        @DisplayName("newPassword can be updated via setter")
        void setter_updatesNewPassword() {
            ChangePasswordRequest req = new ChangePasswordRequest();
            req.setNewPassword("FirstPass1");
            req.setNewPassword("SecondPass2");
            assertThat(req.getNewPassword()).isEqualTo("SecondPass2");
        }
    }

    // =========================================================================
    // LoginRequest
    // =========================================================================

    @Nested
    @DisplayName("LoginRequest")
    class LoginRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for all fields")
        void settersAndGetters_roundTrip() {
            LoginRequest req = new LoginRequest();
            req.setEnterpriseId("EMP050");
            req.setPassword("MySecretPass1");

            assertThat(req.getEnterpriseId()).isEqualTo("EMP050");
            assertThat(req.getPassword()).isEqualTo("MySecretPass1");
        }

        @Test
        @DisplayName("no-args constructor: all fields null")
        void noArgsConstructor_allNull() {
            LoginRequest req = new LoginRequest();
            assertThat(req.getEnterpriseId()).isNull();
            assertThat(req.getPassword()).isNull();
        }

        @Test
        @DisplayName("equals: same credentials produce equal objects")
        void equals_sameValues() {
            LoginRequest a = new LoginRequest();
            a.setEnterpriseId("EMP051");
            a.setPassword("Pass1234");

            LoginRequest b = new LoginRequest();
            b.setEnterpriseId("EMP051");
            b.setPassword("Pass1234");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different enterpriseId produces unequal objects")
        void equals_differentEnterpriseId_notEqual() {
            LoginRequest a = new LoginRequest();
            a.setEnterpriseId("EMP052");
            a.setPassword("SamePass1");

            LoginRequest b = new LoginRequest();
            b.setEnterpriseId("EMP053");
            b.setPassword("SamePass1");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: different password produces unequal objects")
        void equals_differentPassword_notEqual() {
            LoginRequest a = new LoginRequest();
            a.setEnterpriseId("EMP054");
            a.setPassword("PassA1234");

            LoginRequest b = new LoginRequest();
            b.setEnterpriseId("EMP054");
            b.setPassword("PassB5678");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains enterpriseId")
        void toString_containsEnterpriseId() {
            LoginRequest req = new LoginRequest();
            req.setEnterpriseId("EMP055");
            req.setPassword("AnyPass1");
            assertThat(req.toString()).contains("EMP055");
        }

        @Test
        @DisplayName("credentials can be updated via setters")
        void setters_updateCredentials() {
            LoginRequest req = new LoginRequest();
            req.setEnterpriseId("OLD_EID");
            req.setPassword("OldPass1");
            req.setEnterpriseId("NEW_EID");
            req.setPassword("NewPass2");

            assertThat(req.getEnterpriseId()).isEqualTo("NEW_EID");
            assertThat(req.getPassword()).isEqualTo("NewPass2");
        }
    }

    // =========================================================================
    // ReviewRequest
    // =========================================================================

    @Nested
    @DisplayName("ReviewRequest")
    class ReviewRequestTests {

        @Test
        @DisplayName("setters and getters round-trip for all fields")
        void settersAndGetters_roundTrip() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("APPROVE");
            req.setComment("Looks good to me");

            assertThat(req.getAction()).isEqualTo("APPROVE");
            assertThat(req.getComment()).isEqualTo("Looks good to me");
        }

        @Test
        @DisplayName("no-args constructor: all fields null")
        void noArgsConstructor_allNull() {
            ReviewRequest req = new ReviewRequest();
            assertThat(req.getAction()).isNull();
            assertThat(req.getComment()).isNull();
        }

        @Test
        @DisplayName("comment is optional and can be null")
        void comment_optional() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("REJECT");
            assertThat(req.getComment()).isNull();
        }

        @Test
        @DisplayName("REJECT action can be set")
        void action_reject() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("REJECT");
            assertThat(req.getAction()).isEqualTo("REJECT");
        }

        @Test
        @DisplayName("APPROVE action can be set")
        void action_approve() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("APPROVE");
            assertThat(req.getAction()).isEqualTo("APPROVE");
        }

        @Test
        @DisplayName("equals: same values produce equal objects")
        void equals_sameValues() {
            ReviewRequest a = new ReviewRequest();
            a.setAction("APPROVE");
            a.setComment("Correct");

            ReviewRequest b = new ReviewRequest();
            b.setAction("APPROVE");
            b.setComment("Correct");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different action produces unequal objects")
        void equals_differentAction_notEqual() {
            ReviewRequest a = new ReviewRequest();
            a.setAction("APPROVE");

            ReviewRequest b = new ReviewRequest();
            b.setAction("REJECT");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: different comment produces unequal objects")
        void equals_differentComment_notEqual() {
            ReviewRequest a = new ReviewRequest();
            a.setAction("REJECT");
            a.setComment("Comment A");

            ReviewRequest b = new ReviewRequest();
            b.setAction("REJECT");
            b.setComment("Comment B");

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains action field")
        void toString_containsAction() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("APPROVE");
            assertThat(req.toString()).contains("APPROVE");
        }

        @Test
        @DisplayName("action can be updated via setter")
        void setter_updatesAction() {
            ReviewRequest req = new ReviewRequest();
            req.setAction("APPROVE");
            req.setAction("REJECT");
            assertThat(req.getAction()).isEqualTo("REJECT");
        }
    }

    // =========================================================================
    // McqResponse
    // =========================================================================

    @Nested
    @DisplayName("McqResponse")
    class McqResponseTests {

        @Test
        @DisplayName("no-args constructor: all fields are null")
        void noArgsConstructor_allNull() {
            McqResponse res = new McqResponse();
            assertThat(res.getId()).isNull();
            assertThat(res.getQuestionStem()).isNull();
            assertThat(res.getOptionA()).isNull();
            assertThat(res.getDifficulty()).isNull();
            assertThat(res.getStatus()).isNull();
            assertThat(res.getComments()).isNull();
            assertThat(res.getAiWarning()).isNull();
            assertThat(res.getAiScore()).isNull();
        }

        @Test
        @DisplayName("setters and getters round-trip for all scalar fields")
        void settersAndGetters_allFields_roundTrip() {
            LocalDateTime now = LocalDateTime.of(2024, 6, 1, 12, 0);
            McqResponse res = new McqResponse();
            res.setId(1L);
            res.setQuestionStem("What is JVM?");
            res.setOptionA("Java Virtual Machine");
            res.setOptionB("Other B");
            res.setOptionC("Other C");
            res.setOptionD("Other D");
            res.setCorrectAnswer("A");
            res.setDifficulty(Difficulty.EASY);
            res.setStatus(McqStatus.APPROVED);
            res.setTechStackId(10L);
            res.setTechStackName("Java");
            res.setTopicId(20L);
            res.setTopicName("JVM Internals");
            res.setCreatorEnterpriseId("EMP001");
            res.setCreatorFullName("Alice Smith");
            res.setReviewerEnterpriseId("EMP002");
            res.setReviewerFullName("Bob Jones");
            res.setVersion(3);
            res.setCreatedAt(now);
            res.setUpdatedAt(now.plusDays(1));
            res.setAiWarning("Possible ambiguity");
            res.setAiScore(85);
            res.setAiRisk("AI");

            assertThat(res.getId()).isEqualTo(1L);
            assertThat(res.getQuestionStem()).isEqualTo("What is JVM?");
            assertThat(res.getOptionA()).isEqualTo("Java Virtual Machine");
            assertThat(res.getOptionB()).isEqualTo("Other B");
            assertThat(res.getOptionC()).isEqualTo("Other C");
            assertThat(res.getOptionD()).isEqualTo("Other D");
            assertThat(res.getCorrectAnswer()).isEqualTo("A");
            assertThat(res.getDifficulty()).isEqualTo(Difficulty.EASY);
            assertThat(res.getStatus()).isEqualTo(McqStatus.APPROVED);
            assertThat(res.getTechStackId()).isEqualTo(10L);
            assertThat(res.getTechStackName()).isEqualTo("Java");
            assertThat(res.getTopicId()).isEqualTo(20L);
            assertThat(res.getTopicName()).isEqualTo("JVM Internals");
            assertThat(res.getCreatorEnterpriseId()).isEqualTo("EMP001");
            assertThat(res.getCreatorFullName()).isEqualTo("Alice Smith");
            assertThat(res.getReviewerEnterpriseId()).isEqualTo("EMP002");
            assertThat(res.getReviewerFullName()).isEqualTo("Bob Jones");
            assertThat(res.getVersion()).isEqualTo(3);
            assertThat(res.getCreatedAt()).isEqualTo(now);
            assertThat(res.getUpdatedAt()).isEqualTo(now.plusDays(1));
            assertThat(res.getAiWarning()).isEqualTo("Possible ambiguity");
            assertThat(res.getAiScore()).isEqualTo(85);
            assertThat(res.getAiRisk()).isEqualTo("AI");
        }

        @Test
        @DisplayName("builder creates instance with all fields set")
        void builder_allFields_roundTrip() {
            LocalDateTime now = LocalDateTime.of(2024, 7, 15, 10, 30);
            McqResponse res = McqResponse.builder()
                    .id(5L)
                    .questionStem("What is Spring Boot?")
                    .optionA("A framework")
                    .optionB("A language")
                    .optionC("A database")
                    .optionD("An OS")
                    .correctAnswer("A")
                    .difficulty(Difficulty.MEDIUM)
                    .status(McqStatus.DRAFT)
                    .techStackId(2L)
                    .techStackName("Spring")
                    .topicId(3L)
                    .topicName("Spring MVC")
                    .creatorEnterpriseId("EMP010")
                    .creatorFullName("Carol White")
                    .reviewerEnterpriseId("EMP011")
                    .reviewerFullName("Dave Brown")
                    .version(1)
                    .createdAt(now)
                    .updatedAt(now)
                    .aiWarning(null)
                    .aiScore(70)
                    .aiRisk("LOW")
                    .build();

            assertThat(res.getId()).isEqualTo(5L);
            assertThat(res.getQuestionStem()).isEqualTo("What is Spring Boot?");
            assertThat(res.getDifficulty()).isEqualTo(Difficulty.MEDIUM);
            assertThat(res.getStatus()).isEqualTo(McqStatus.DRAFT);
            assertThat(res.getTechStackName()).isEqualTo("Spring");
            assertThat(res.getCreatorEnterpriseId()).isEqualTo("EMP010");
            assertThat(res.getAiScore()).isEqualTo(70);
            assertThat(res.getAiWarning()).isNull();
        }

        @Test
        @DisplayName("builder partial fields: unset fields are null")
        void builder_partialFields_unsetAreNull() {
            McqResponse res = McqResponse.builder()
                    .id(99L)
                    .questionStem("Partial question")
                    .build();

            assertThat(res.getId()).isEqualTo(99L);
            assertThat(res.getQuestionStem()).isEqualTo("Partial question");
            assertThat(res.getOptionA()).isNull();
            assertThat(res.getDifficulty()).isNull();
            assertThat(res.getStatus()).isNull();
            assertThat(res.getComments()).isNull();
            assertThat(res.getAiScore()).isNull();
        }

        @Test
        @DisplayName("equals: two instances with same values are equal")
        void equals_sameValues_equal() {
            McqResponse a = McqResponse.builder()
                    .id(1L).questionStem("Q?").correctAnswer("A")
                    .difficulty(Difficulty.HARD).status(McqStatus.APPROVED)
                    .build();
            McqResponse b = McqResponse.builder()
                    .id(1L).questionStem("Q?").correctAnswer("A")
                    .difficulty(Difficulty.HARD).status(McqStatus.APPROVED)
                    .build();
            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("equals: different id produces unequal objects")
        void equals_differentId_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q?").build();
            McqResponse b = McqResponse.builder().id(2L).questionStem("Q?").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: different questionStem produces unequal objects")
        void equals_differentQuestionStem_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Question A?").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Question B?").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("toString contains id and questionStem")
        void toString_containsKeyFields() {
            McqResponse res = McqResponse.builder()
                    .id(77L)
                    .questionStem("What is polymorphism?")
                    .build();
            String str = res.toString();
            assertThat(str).contains("77").contains("What is polymorphism?");
        }

        @Test
        @DisplayName("all Difficulty enum values can be set")
        void difficulty_allEnumValues() {
            for (Difficulty d : Difficulty.values()) {
                McqResponse res = new McqResponse();
                res.setDifficulty(d);
                assertThat(res.getDifficulty()).isEqualTo(d);
            }
        }

        @Test
        @DisplayName("all McqStatus enum values can be set")
        void status_allMcqStatusValues() {
            for (McqStatus s : McqStatus.values()) {
                McqResponse res = new McqResponse();
                res.setStatus(s);
                assertThat(res.getStatus()).isEqualTo(s);
            }
        }

        @Test
        @DisplayName("comments list is preserved via setter")
        void comments_listPreserved() {
            CommentResponse c1 = CommentResponse.builder().id(1L).comment("First").build();
            CommentResponse c2 = CommentResponse.builder().id(2L).comment("Second").build();
            McqResponse res = new McqResponse();
            res.setComments(List.of(c1, c2));
            assertThat(res.getComments()).hasSize(2).containsExactly(c1, c2);
        }

        @Test
        @DisplayName("comments list via builder is preserved")
        void comments_listViaBuilder() {
            CommentResponse c = CommentResponse.builder().id(10L).comment("Nice").build();
            McqResponse res = McqResponse.builder()
                    .id(3L)
                    .comments(List.of(c))
                    .build();
            assertThat(res.getComments()).hasSize(1);
            assertThat(res.getComments().get(0).getComment()).isEqualTo("Nice");
        }

        @Test
        @DisplayName("ai fields can be null")
        void aiFields_canBeNull() {
            McqResponse res = McqResponse.builder().id(4L).build();
            assertThat(res.getAiScore()).isNull();
            assertThat(res.getAiRisk()).isNull();
            assertThat(res.getAiWarning()).isNull();
        }

        @Test
        @DisplayName("reviewer fields are nullable")
        void reviewerFields_canBeNull() {
            McqResponse res = McqResponse.builder()
                    .id(5L)
                    .creatorEnterpriseId("EMP001")
                    .build();
            assertThat(res.getReviewerEnterpriseId()).isNull();
            assertThat(res.getReviewerFullName()).isNull();
        }

        // ── Additional tests to boost branch coverage in equals() ───────────

        @Test
        @DisplayName("equals(null) returns false")
        void equals_null_returnsFalse() {
            McqResponse res = McqResponse.builder().id(1L).questionStem("Q").build();
            assertThat(res.equals(null)).isFalse();
        }

        @Test
        @DisplayName("equals(different type) returns false")
        void equals_differentType_returnsFalse() {
            McqResponse res = McqResponse.builder().id(1L).questionStem("Q").build();
            assertThat(res.equals("not-a-response")).isFalse();
        }

        @Test
        @DisplayName("equals(same instance) returns true")
        void equals_sameInstance_returnsTrue() {
            McqResponse res = McqResponse.builder().id(1L).questionStem("Q").build();
            assertThat(res.equals(res)).isTrue();
        }

        @Test
        @DisplayName("hashCode is consistent across multiple calls")
        void hashCode_consistent() {
            McqResponse res = McqResponse.builder()
                    .id(10L).questionStem("Q").difficulty(Difficulty.EASY).build();
            assertThat(res.hashCode()).isEqualTo(res.hashCode());
        }

        @Test
        @DisplayName("equals: same id but different optionA produces unequal objects")
        void equals_differentOptionA_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q").optionA("AAA").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q").optionA("BBB").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: same id, questionStem, optionA but different optionB produces unequal objects")
        void equals_differentOptionB_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q").optionA("A").optionB("X").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q").optionA("A").optionB("Y").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: differing on correctAnswer produces unequal objects")
        void equals_differentCorrectAnswer_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("B").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: differing on difficulty produces unequal objects")
        void equals_differentDifficulty_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.HARD).build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: differing on status produces unequal objects")
        void equals_differentStatus_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT).build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.APPROVED).build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: differing on techStackId produces unequal objects")
        void equals_differentTechStackId_notEqual() {
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(1L).build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(2L).build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: differing on aiScore produces unequal objects")
        void equals_differentAiScore_notEqual() {
            LocalDateTime ts = LocalDateTime.of(2024, 1, 1, 0, 0);
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(1L).techStackName("Java").topicId(1L).topicName("OOP")
                    .creatorEnterpriseId("E1").creatorFullName("Alice")
                    .reviewerEnterpriseId("E2").reviewerFullName("Bob")
                    .comments(List.of()).version(1).createdAt(ts).updatedAt(ts)
                    .aiWarning(null).aiScore(80).aiRisk("LOW").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(1L).techStackName("Java").topicId(1L).topicName("OOP")
                    .creatorEnterpriseId("E1").creatorFullName("Alice")
                    .reviewerEnterpriseId("E2").reviewerFullName("Bob")
                    .comments(List.of()).version(1).createdAt(ts).updatedAt(ts)
                    .aiWarning(null).aiScore(95).aiRisk("LOW").build();
            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals: two fully-populated identical objects are equal and have same hashCode")
        void equals_fullyPopulated_sameValues_equal() {
            LocalDateTime ts = LocalDateTime.of(2024, 1, 1, 0, 0);
            CommentResponse c = CommentResponse.builder().id(1L).build();
            McqResponse a = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(1L).techStackName("Java").topicId(1L).topicName("OOP")
                    .creatorEnterpriseId("E1").creatorFullName("Alice")
                    .reviewerEnterpriseId("E2").reviewerFullName("Bob")
                    .comments(List.of(c)).version(1).createdAt(ts).updatedAt(ts)
                    .aiWarning("warn").aiScore(80).aiRisk("LOW").build();
            McqResponse b = McqResponse.builder().id(1L).questionStem("Q")
                    .optionA("A").optionB("B").optionC("C").optionD("D")
                    .correctAnswer("A").difficulty(Difficulty.EASY).status(McqStatus.DRAFT)
                    .techStackId(1L).techStackName("Java").topicId(1L).topicName("OOP")
                    .creatorEnterpriseId("E1").creatorFullName("Alice")
                    .reviewerEnterpriseId("E2").reviewerFullName("Bob")
                    .comments(List.of(c)).version(1).createdAt(ts).updatedAt(ts)
                    .aiWarning("warn").aiScore(80).aiRisk("LOW").build();
            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }
    }
}
