package com.accenture.quizhub.entity;

import com.accenture.quizhub.enums.Difficulty;
import com.accenture.quizhub.enums.McqStatus;
import com.accenture.quizhub.enums.QuestionType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(
    name = "mcqs",
    indexes = {
        @Index(name = "idx_mcq_status",        columnList = "status"),
        @Index(name = "idx_mcq_creator",       columnList = "creator_id"),
        @Index(name = "idx_mcq_reviewer",      columnList = "reviewer_id"),
        @Index(name = "idx_mcq_tech_stack",    columnList = "tech_stack_id"),
        @Index(name = "idx_mcq_status_creator", columnList = "status, creator_id")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Mcq {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "question_stem", nullable = false, columnDefinition = "TEXT")
    private String questionStem;

    @Column(name = "option_a", columnDefinition = "TEXT")
    private String optionA;

    @Column(name = "option_b", columnDefinition = "TEXT")
    private String optionB;

    @Column(name = "option_c", columnDefinition = "TEXT")
    private String optionC;

    @Column(name = "option_d", columnDefinition = "TEXT")
    private String optionD;

    @Column(name = "correct_answer", columnDefinition = "TEXT")
    private String correctAnswer;

    /** JSON payload for advanced question types (ordering items, matching pairs, code blocks, etc.) */
    @Column(name = "content_json", columnDefinition = "TEXT")
    private String contentJson;

    @Enumerated(EnumType.STRING)
    @Column(name = "question_type", nullable = false, length = 30)
    @Builder.Default
    private QuestionType questionType = QuestionType.SINGLE;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Difficulty difficulty;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private McqStatus status = McqStatus.DRAFT;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tech_stack_id")
    @BatchSize(size = 20)
    private TechStack techStack;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "topic_id")
    @BatchSize(size = 20)
    private Topic topic;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "creator_id", nullable = false)
    @BatchSize(size = 20)
    private User creator;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewer_id")
    @BatchSize(size = 20)
    private User reviewer;

    @OneToMany(mappedBy = "mcq", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @BatchSize(size = 20)
    private List<ReviewComment> comments;

    @Version
    private Integer version;

    @Column(name = "ai_score")
    private Integer aiScore;

    @Column(name = "ai_risk", length = 10)
    private String aiRisk;

    @Transient
    private String aiWarning;

    /** Whether this MCQ was generated by AI */
    @Column(name = "ai_generated")
    @Builder.Default
    private Boolean aiGenerated = false;

    /** Optional image URL for image-based questions */
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    /** Optional video URL for video-based questions */
    @Column(name = "video_url", length = 500)
    private String videoUrl;

    /** Media type: TEXT (default), IMAGE, VIDEO */
    @Column(name = "media_type", length = 10)
    @Builder.Default
    private String mediaType = "TEXT";

    /** Number of times this MCQ has been rejected by reviewers */
    @Column(name = "rejection_count")
    @Builder.Default
    private Integer rejectionCount = 0;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
